version: '3.8'
services:
  server:
    restart: always
    build: server
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - TZ=Europe/Moscow
      - PORT=2801
    ports:
      - 2801:2801
      
